spring.application.name=ecommerce

# H2 Database (se reinicia al parar la app)
# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console

# MySQL (levantá el servidor antes de arrancar la app)
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=RubiyMilita
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
# 1. Clave Secreta JWT (Secret Key)
# Esta clave se usa para firmar y validar el token. 
# Idealmente, use una variable de entorno en producción.
# TODO: ssanchez - sacar la clave secreta de aquí en producción, almacenarla en un lugar seguro como una variable de entorno
jwt.secret=miClaveSecretaDe32CaracteresParaJWT2025

# 2. Tiempo de Expiración del Token (Expiration Time)
# Define por cuánto tiempo será válido el token, en milisegundos (ms).
# Ejemplo: 24 horas = 86400000 ms
jwt.expiration=86400000